# Generated by Django 2.2.16 on 2021-12-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20211211_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follow'},
        ),
    ]
